### ISSUE TITLE
Adding property attributes to custom-element produces an error

### ISSUE THREAD

**Issue by Roymandersloot** [centaur54dev/ckeditor5-custom-element#1]
Hi,

I'm working on an Angular project in which I need to implement a html-text-editor. I'm using the  CKEditor. I've created a custom build so I can use your plugin in my project. Everything works fine until I try to add the property 'attributes' to my custom tag. This gives the following error in my console:

```
ckeditor-ckeditor5-angular.js:326 ReferenceError: attributeToAttribute is not defined
    at Zg.init (ckeditor.js:5)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
```

My CustomElement implementation is like this:
```
ClassicEditor.defaultConfig = {
    toolbar: {
        items: [
            'custom-element-tagname1'
        ]
    },
    CustomElement:{
        items:[
            {tag: 'tagname1', placeholder: 'some text', attributes:{name:'foo'}, inline:true, editable:false}
        ]
    },
}
```

**Comment by centaur54dev** [comment]
Maybe a dependency issue? Which version of ckeditor5 are you using? Also could you use npm-check-updates to check for any out of date dependencies?

**Comment by Roymandersloot** [comment]
Thanks for the quick reply.

I'm using the following versions:
```
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "ckeditor5-custom-element": "^2.0.3",
```
And my custom build is derived from ckeditor5-build-classic@12.1.0.

These are as far as i can tell with the ncu command the latest packages.

**Comment by centaur54dev** [comment]
Except for angular, i am using the same packages without errors. Could you please post the output of these commands:
`npm list @ckeditor/ckeditor5-engine`
`npm list @ckeditor/ckeditor5-core`

**Comment by Roymandersloot** [comment]
Thanks again for the quick reply. This is the output from the two commands.

npm list @ckeditor/ckeditor5-engine
```
c:\...\ClientApp
`-- ckeditor5-custom-element@2.0.3
  +-- @ckeditor/ckeditor5-core@12.1.0
  | `-- @ckeditor/ckeditor5-engine@13.1.0
  `-- @ckeditor/ckeditor5-widget@11.0.1
    `-- @ckeditor/ckeditor5-engine@13.1.0  deduped
```

npm list @ckeditor/ckeditor5-core
```
c:\...\ClientApp
`-- ckeditor5-custom-element@2.0.3
  +-- @ckeditor/ckeditor5-core@12.1.0
  +-- @ckeditor/ckeditor5-ui@12.1.0
  | `-- @ckeditor/ckeditor5-core@12.1.0  deduped
  `-- @ckeditor/ckeditor5-widget@11.0.1
    `-- @ckeditor/ckeditor5-core@12.1.0  deduped
```

**Comment by centaur54dev** [comment]
Unfortunately, I can't find an apparent dependency issue here. The reported error indicates that a release of ckeditor5-engine older than v.13 is used. Are there any other plugins loaded?

I have created a custom build of the classic-editor with only my plugin loaded. It is available in the 'test-builds' folder. Also a jsfiddle demonstrating the use of the custom build can be found here:
 [https://jsfiddle.net/centaur54dev/dm96143q/](https://jsfiddle.net/centaur54dev/dm96143q/).

**Comment by centaur54dev** [comment]
Do you have any new updates regarding this issue? Have you resolved the cause?

**Comment by Roymandersloot** [comment]
I could not solve the problem. It is probably something in my solution that does not go well together. Finally, another editor was chosen to work with.

**Comment by young-george** [comment]
I think this is because line 91 of customelem_ui.js is `editor.conversion.for('upcast').add(attributeToAttribute({` but (I think) should be `editor.conversion.for('upcast').attributeToAttribute(({`.

**Comment by centaur54dev** [comment]
@young-george thanks for the finding. Version 2.0.4 fixes it.
