### ISSUE TITLE
allowedAttributes not working

### ISSUE THREAD

**Issue by novayadi85** [centaur54dev/ckeditor5-custom-element#10]
Hi, 

I tried yours, but I dont find any allowed attributes working.
```
items: [
                {
                    tag: 'tagname1', 
                    placeholder: 'some text', 
                    attributes: {
                        name:'ABCD',

                    }, 
                    inline: true , 
                    editable: false
                }, 
.....
```

and I try to insert text by 

```
var viewFragment = editor.data.processor.toView( content );
var modelFragment = editor.data.toModel( viewFragment );
editor.model.insertContent( modelFragment );
```

the result is only : 
![image](https://user-images.githubusercontent.com/13636942/84123727-cfefa380-aa6c-11ea-8407-fff1da8ba881.png)

Could you please help me, what is wrong?

Thanks

**Comment by centaur54dev** [comment]
Hmm, do you have a reason to insert the content programmatically? The plugin works with the toolbar. Have  you tried to add a toolbar button and see if it works? Like this:

```
toolbar: {
        items: [
            ...
            'custom-element-tagname1',
            ...
            ]
    },
```

**Comment by novayadi85** [comment]
I do that because I have external function to change text inside the tag. 
actually I have solved this problem . 

I have another problem, how to check if the element is still exsist? 
Now even if using toolbar, every click the toolbar that always create new element.

**Comment by centaur54dev** [comment]
Glad you have solved the problem. This issue is closed. 
Opening new issue for the new problem.
