### ISSUE TITLE
how to check if the element is still exsist?

### ISSUE THREAD

**Issue by centaur54dev** [centaur54dev/ckeditor5-custom-element#11]
_Originally posted by @novayadi85 in https://github.com/centaur54dev/ckeditor5-custom-element/issues/10#issuecomment-641584877_

_I have another problem, how to check if the element is still exsist? 
Now even if using toolbar, every click the toolbar that always create new element._

**Comment by centaur54dev** [comment]
Yes this is normal. The plugin creates a new element whenever it is asked to. It is expected that many custom elements can be present at the same time in a document. 

Please elaborate on your use case.

**Comment by novayadi85** [comment]
Hi I got the solution for this issue :
I modify in execute function  and add variable replaceOnExsist in constructor
```
model.change( writer => {
    if(this.replaceOnExsist){
        const selection = model.document.selection;
        const range = selection.getFirstRange();
        let isNew = true;
        for (const item of range.getItems()) {
                // we can check more criteria here, eq: textProxy or Element
                if(item.name == this.tagName){
                    isNew = false;
                }
            }
   
    if(!isNew) ....  // do your action here 
}

....

})
```

I solved for my issue with that,  thanks for your plugin 👍 
Thanks

**Comment by centaur54dev** [comment]
Thanks for sharing your solution. I have done a quick check and i confirm that the plugin does not insert the same custom element nested inside another one. No issue there. 

By your words, I get the plugin works as expected, so i close this issue.
