### ISSUE TITLE
Cannot resolve 'ckeditor5-custom-element'

### ISSUE THREAD

**Issue by ansorensen** [centaur54dev/ckeditor5-custom-element#3]
When compiling in my webpack project, I get the error `Module not found: Error: Can't resolve 'ckeditor5-custom-element'`

I am importing the same as any node_module:
`import CustomElementPlugin from 'ckeditor5-custom-element'`

I noticed that your package.json points to 'customelement.js' as your main.  However, you don't have a top level customelement.js, it's in 'src/customelement.js'. When I manually change your package.json in node_modules to use 'src/customelement.js' for main, I can use your library as normal.
`"main": "src/customelement.js",`

**Comment by centaur54dev** [comment]
@ansorensen thanks for the finding! I missed this.
New patch 2.0.5 includes the fix.
