### ISSUE TITLE
elements broken after editing a second time

### ISSUE THREAD

**Issue by dirkjf** [centaur54dev/ckeditor5-custom-element#4]
I have created an element: 

```
CustomElement:{
    items:[
        {tag: 'div', placeholder: 'placeholder text',
            attributes:{class: 'bg-light' },
            inline:true, editable:false},
    ]
},
```
The class `bg-light` is simply to test with a background color. 

All works when inserting and when I save the first time. However, when I want to edit again, my element is removed and in return I get: 
``` 
<p><br data-cke-filler="true"></p>
<p>placeholder text</p>
<p><br data-cke-filler="true"></p>

**Comment by centaur54dev** [comment]
This is not expected behavior. Are you saving and then loading the document with the setData/getData commands? 
```
   var html = editor.getData()
   ....
   editor.setData(html)
```
Perhaps ckeditor5 converts div to p internally. Have you tried with custom tag (i.e. tag: 'mydiv')

edit: sorry for the delayed response, i missed the notification

**Comment by centaur54dev** [comment]
Closed. No feedback received for a  long time.
