### ISSUE TITLE
Support safeHtml placeholder

### ISSUE THREAD

**Issue by Routhinator** [centaur54dev/ckeditor5-custom-element#7]
I'm trying to create a pagebreak element that has an html placeholder with an FA Icon to display nicely to the user. Unfortunately the plugin is designed to always treat the placeholder as unsafe and escape it.

I propose that there be a flag to indicate that the placeholder should be treated as safeHTML.

For reference, this is the output I need to achieve:

```html
<pagebreak><p style="text-align:center">--- <i class="fa fa-file-text-o"></i> ---</p></pagebreak>
```

This is the config I'm using:

```typescript
  public ckEditorConfig = {
    toolbar: [
      'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'code', 'alignment', 'custom-element-pagebreak',
      '|', 'undo', 'redo',
      '|', 'removeFormat'
    ],
    placeholder: 'This is where you type the body of your writing. Use the controls above for formatting.',
    CustomElement: {
      items: [
        {
          tag: 'pagebreak',
          placeholder: '<p style="text-align:center">--- <i class="fa fa-file-text-o"></i> ---</p>',
          inline: false,
        }
      ]
    }
  };
```

And this is what I get in the output currently:

```html
<pagebreak>&lt;p style="text-align:center"&gt;--- &lt;i class="fa fa-file-text-o"&gt;&lt;/i&gt; ---&lt;/p&gt;</pagebreak>
```

I'd propose a boolean for this like `safePlaceholder` that defaults to false.

**Comment by Routhinator** [comment]
I dug around for a bit @centaur54dev and I cannot seem to find a ckeditor function that would allow something like this.. so I've added a feature request for an `.appendHtml` function that would make this implementation possible.


https://github.com/ckeditor/ckeditor5/issues/6337

**Comment by centaur54dev** [comment]
@Routhinator thanks for the suggestion, though ckeditor5 does not permit direct HTML code ( i believe this is by design). For the time being you could put as placeholder something like this:

```placeholder: '[[-----------BR------------]]'```

and replace it when you fetch the HTML from the editor (not as fancy as an image though).

**Comment by Routhinator** [comment]
Not as user friendly but it will work.

Another way I supposed this could be approached is child elements, in an array on the main elements definition, and then looping them and calling writer.createElement on each child and appending it to the parent with appendElement.
