### ISSUE TITLE
How do I provide an icon in ckeditor5-angular

### ISSUE THREAD

**Issue by Routhinator** [centaur54dev/ckeditor5-custom-element#8]
I have been banging my head on this one. I cannot import an Icon as documented in Typescript, it is not valid code. It seems importing an svg as an object is not supported...

**Comment by Routhinator** [comment]
Probably should add something to the docs based on this when I find a better way.. https://github.com/ckeditor/ckeditor5-angular/issues/170

**Comment by Routhinator** [comment]
This is the best solution I have so far.. not a very typescript way..

```typescript
const pagebreakIcon = require('!!raw-loader?!../../../../assets/images/icons/pagebreak.svg');

  public ckEditorConfig = {
    toolbar: [
      'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'code', 'alignment',
      '|', 'indent', 'outdent',
      '|', 'custom-element-pagebreak',
      '|', 'undo', 'redo',
      '|', 'removeFormat'
    ],
    placeholder: 'This is where you type the body of your writing. Use the controls above for formatting.',
    CustomElement: {
      items: [
        {
          tag: 'pagebreak',
          placeholder: '[[--------pagebreak--------]]',
          icon: pagebreakIcon.default,
          inline: false,
        }
      ]
    }
  };
```

**Comment by centaur54dev** [comment]
Or you could paste the svg code directly to a variable, if you don't mind loosing the flexibility to edit icons regularly. 

I am afraid your last solution is probably the best you could get. This is a Typescript restriction. Unless the ck5 devs allow other options for assigning an icon to a ButtonView.

**Comment by centaur54dev** [comment]
@Routhinator  is this issue still relevant with this plugin?

**Comment by Routhinator** [comment]
No we can close this.
